README.md

Updated LTS proposal based on todays LTS WG discussion

lts: update the proposed lts plan

---

README.md

Update LTS plan detail. Remove the "Proposed" tag, add detail about 
named LTS releases.
/cc @nodejs/lts .. quick review please before I land?

readme: update LTS plan detail

---

README.md

update to reflect reality (v4.2.0 LTS)

---

README.md

Update the table to reflect the current status of v0.10 and v7

doc: update table to show v0.10 EOL and v7 N/A

---

README.md

I've always found "Not Available" a strange way to say "None" in this table.

make the LTS statuses in the table for Current clearer

---

doc/meetings/2017-04-24.md

Just realised these were still outstanding from the last meeting.

doc: add minutes for meeting 2017-04-24

---

doc/meetings/2017-09-19.md

Fixes: https://github.com/nodejs/Release/issues/244

doc: add meeting minutes for 2017-09-19

---

README.md

closes: https://github.com/nodejs/Release/issues/249

docs: update LTS date for 8.x

---

README.md

Fixes: https://github.com/nodejs/Release/issues/258

doc: update CTC -> TSC

---

README.md

This file does not exist in the repository

remove iCal file link

---

README.md

Now the repo covers Current releases as well, it should be clear about
their status.
Refs: https://twitter.com/wa7son/status/950300918347714560
cc/ @watson  @bnb

doc: current releases are still End-of-Life

---

GOVERNANCE.md
README.md

Formalizing process around adding releasers as we have some folks nominated

doc: add process for adding new releasers

---

README.md

Ref: https://github.com/nodejs/node/pull/21114

doc: add Michaël Zasso to Releasers team

---

README.md

This should not be in the readme

doc: remove reference to unmaintained cal

---

README.md

doc: update members with ncu-team

---

GOVERNANCE.md

This was requested by the docker team

doc: open PR rather than issue with docker repo

---

doc/meetings/2019-06-20.md
doc/meetings/2019-08-29.md

Fixes: https://github.com/nodejs/Release/issues/472

doc: add minutes for 2019-08-29

---

README.md

Refs: https://github.com/nodejs/Release/issues/458

meta: swap active and maintenance periods

---

doc/meetings/2019-12-05.md

Fixes: https://github.com/nodejs/Release/issues/509

doc: add minutes for 2019-12-05

---

doc/meetings/2019-12-19.md

Fixes: https://github.com/nodejs/Release/issues/512

doc: add minutes for 2019-12-19

---

README.md

doc: mark Node.js 8 End-of-Life

---

doc/meetings/2020-01-16.md

Please let me know if I have missed your name from the attendee list 🙏

doc: add minutes for 2020-01-16

---

README.md

Blanket approval from https://github.com/nodejs/build/issues/2022

doc: remove @gibfahn from Release teams

---

doc/meetings/2020-01-30.md

Fixes: https://github.com/nodejs/Release/issues/527
Please let me know/suggest changes if you were there - I just copied the names over from the minutes

doc: add minutes for 2020-01-30

---

README.md

Based on https://github.com/nodejs/node/pull/31725, #499 (comment)
Fixes: #534

doc: move @Fishrock123 to emeritus

---

doc/meetings/2020-02-27.md

Please let me know if I missed your name off the attendee list.
Also thank you @darcyclarke for taking great notes during the meeting :pray:

doc: add minutes for 2020-02-27

---

doc/meetings/2020-03-12.md

Please let me know if I missed your name off of the attendees list 🙏
Fixes: https://github.com/nodejs/Release/issues/546

doc: add minutes for 2020-03-12

---

README.md

Closes: https://github.com/nodejs/Release/issues/550

doc: update membership list

---

doc/meetings/2020-03-26.md

Please let me know if I missed you off the attendee list 🙏

doc: add minutes for 2020-03-26

---

README.md

Closes: https://github.com/nodejs/Release/issues/549

doc: move LTS members to emeritus

---

doc/meetings/2020-04-09.md

Please comment if I missed you off that attendees list.
Fixes: https://github.com/nodejs/Release/issues/564

doc: add minutes for 2020-04-09

---

doc/meetings/2020-05-07.md

Fixes: https://github.com/nodejs/Release/issues/575
Let me know if I missed you off of the attendees 🙏

doc: add minutes for 2020-05-07

---

README.md

Fixes: https://github.com/nodejs/Release/issues/565
Nomination has been open a while

doc: ncu-team sync update

---

doc/meetings/2020-05-21.md

Fixes: https://github.com/nodejs/Release/issues/579

doc: add minutes for 2020-05-21

---

README.md

Maintenance start is listed as 2020-05-19

chore: Flip v10 to Maintenance

---

doc/meetings/2020-07-02.md

Fixes: https://github.com/nodejs/Release/issues/589

doc: add minutes for meeting 2020-07-02

---

doc/meetings/2020-07-16.md

Fixes: https://github.com/nodejs/Release/issues/593

doc: add minutes for meeting 2020-07-16

---

README.md

Refs: https://github.com/nodejs/Release/issues/585

doc: add @richardlau to releasers

---

README.md

Synced README.md with `ncu-team sync README.md`.

doc: add @ruyadorno to releasers

---

doc/meetings/2020-08-13.md

Fixes: https://github.com/nodejs/Release/issues/599

doc: add minutes for meeting 2020-08-13

---

doc/meetings/2020-08-27.md

Fixes: https://github.com/nodejs/Release/issues/606

doc: add minutes for meeting 2020-08-27

---

doc/meetings/2020-09-10.md

Fixes: https://github.com/nodejs/Release/issues/609

doc: add minutes for meeting 2020-09-10

---

doc/meetings/2020-09-24.md

Fixes: https://github.com/nodejs/Release/issues/611

doc: add minutes for meeting 2020-09-24

---

GOVERNANCE.md

Add documentation of creating a "Node" key since some of the docs reference this option too.

doc: add flag for output of RSA keys

---

doc/meetings/2020-10-08.md

Fixes: https://github.com/nodejs/Release/issues/615

doc: add minutes for meeting 2020-10-08

---

README.md

Add @danielleadams to releasers list.

doc: add @danielleadams to releasers

---

doc/meetings/2020-11-05.md

Fixes: https://github.com/nodejs/Release/issues/626

doc: add minutes for 2020-11-05

---

doc/meetings/2020-12-03.md

Fixes: https://github.com/nodejs/Release/issues/630

doc: add minutes for 2020-12-03

---

doc/meetings/2021-01-14.md

Fixes: https://github.com/nodejs/Release/issues/638

doc: add minutes for 2021-01-14

---

doc/meetings/2021-02-11.md

Fixes: https://github.com/nodejs/Release/issues/645
[Belated minutes from 2021-02-11]

doc: add minutes for 2021-02-11

---

README.md

Fixes: https://github.com/nodejs/Release/issues/647

doc: add Danielle to LTS team

---

doc/meetings/2021-04-22.md

Fixes: https://github.com/nodejs/Release/issues/659

doc: add minutes for meeting 2021-04-22

---

doc/meetings/2021-05-20.md

Fixes: https://github.com/nodejs/Release/issues/669

doc: add minutes for meeting 2021-05-20

---

doc/release-guide.md

I figured we needed a home for documentation/guidance such as #561. For now, I think it makes sense for this file to only contain guidance related to this repository, while the specific steps of creating releases remain over in the `releases.md` file in Node.js core.
Open to alternative suggestions (or names) of where this documentation should live. I do think we need this written down somewhere, though.

Schedule update guidance

---

doc/meetings/2021-06-17.md

Fixes: https://github.com/nodejs/Release/issues/678
_Belated 😇_

doc: add minutes for meeting 2021-06-17

---

doc/meetings/2021-07-01.md

Fixes: https://github.com/nodejs/Release/issues/681

doc: add minutes for 2021-07-01

---

doc/meetings/2021-11-04.md

Fixes: https://github.com/nodejs/Release/issues/709

doc: add minutes for meeting 2021-11-04

---

doc/meetings/2021-12-02.md

Fixes: https://github.com/nodejs/Release/issues/713

doc: add minutes for meeting 2021-12-02

---

doc/release-guide.md

That link returns a 404 status code

doc: fix the broken link ref to the `releases.md` file.

---

doc/meetings/2022-01-13.md
doc/meetings/2022-02-10.md
doc/meetings/2022-03-10.md

Closes: https://github.com/nodejs/Release/issues/719
Closes: https://github.com/nodejs/Release/issues/722
Closes: https://github.com/nodejs/Release/issues/732
There aren't really any notes in the documents :(

doc: add minutes for meetings 2022-01 to 2022-03

---

doc/meetings/2022-04-14.md

Closes: https://github.com/nodejs/Release/issues/735

doc: add minutes for meeting 2022-04-14

---

doc/meetings/2022-06-30.md

Closes: https://github.com/nodejs/Release/issues/758

doc: add minutes for meeting 2022-06-30

---

doc/meetings/2022-07-28.md

Closes: https://github.com/nodejs/Release/issues/764

doc: add minutes for meeting 2022-07-28

---

CODENAMES.md

Refs: https://github.com/nodejs/Release/issues/304#issuecomment-1177849487

doc: add codename for J

---

doc/meetings/2023-01-12.md

Fixes: https://github.com/nodejs/Release/issues/814

doc: add minutes for meeting 2023-01-12

---

doc/meetings/2023-03-09.md

Closes: https://github.com/nodejs/Release/issues/830

doc: add minutes for meeting 2023-03-09

---

README.md

Update README.md for version 20

---

doc/meetings/2023-05-09.md

Minutes for the session in the Collaborator Summit 2023 in Vancouver.

doc: add minutes for meeting 2023-05-09

---

doc/meetings/2023-07-27.md

Closes: https://github.com/nodejs/Release/issues/886

doc: add minutes for meeting 2023-07-27

---

doc/meetings/2023-08-24.md

doc: add minutes for meeting 2023-08-24

---

GOVERNANCE.md
doc/meetings/2023-07-27.md

Just found out two small typos in GOVERNANCE and last meeting's notes.

chore: fixing two typos

---

README.md

Ref: https://github.com/nodejs/Release/issues/892#issuecomment-1753243498

Add Ulises to the "Releasers team"

---

doc/meetings/2023-10-19.md

I believe the current minutes are a bit lightweight, feel free to add more notes if wanted 😊 
I'll give it some extra time before landing the PR.
Closes: https://github.com/nodejs/Release/issues/937

doc: add minutes for meeting 2023-10-19

---

doc/meetings/2023-11-16.md

Please feel free to add your thoughts on the proposal to the minutes here as it appears we didn't took any notes on that 😳 cc @richardlau @targos @UlisesGascon

doc: add minutes for meeting 2023-11-16

---

doc/meetings/2024-02-08.md

cc @richardlau @UlisesGascon @marco-ippolito please help me review the minutes as I added a lot to it after the meeting, feel free to add, change or remove anything 😊

doc: add minutes for meeting 2024-02-08

---

README.md

Refs: https://github.com/nodejs/Release/issues/984

doc: add marco-ippolito to releasers

---

GOVERNANCE.md
README.md
doc/release-guide.md

Added punctuation for readability.

docs: added punctuation

---

doc/meetings/2024-05-30.md

close https://github.com/nodejs/Release/issues/1011

Add meeting notes for 2024-05-30

---

doc/meetings/2024-06-27.md

closes https://github.com/nodejs/Release/issues/1021

Add meeting notes for 2024-06-27

---

doc/meetings/2024-09-19.md

Fixes: https://github.com/nodejs/Release/issues/1033
@nodejs/releasers

chore: add minutes for 2024-09-19 meeting

---

README.md

It's been fun, but I simply don't have time to commit to Node.js Releases anymore. Thank y'all!

Move MylesBorins to Emeritus

---

README.md

Refs: https://github.com/nodejs/Release/issues/1036

doc: move releasers to emeritus

---

doc/meetings/2024-10-17.md

Fixes: https://github.com/nodejs/Release/issues/1043

doc: add meeting notes 2024-10-17

---

generateReleasePlan.cjs

Generating those tables is not a job for humans, let's have a script that does the work for us.

add util script to generate release plan tables

---

doc/meetings/2025-05-29.md

Fixes: https://github.com/nodejs/Release/issues/1092

doc: add meeting minutes 2025-05-29

---

doc/meetings/2025-07-24.md

Please review your comment notes if possible 😊 
cc @RafaelGSS @richardlau @marco-ippolito @targos @aduh95

doc: add minutes for meeting 2025-07-24
