nodejs/Release

README.md

as per discussion on nodejs/nodejs.org#493 and in reference to nodejs/nodejs.org#494. We would want to have a link to the picture of the schedule in the readme, instead of a link to the raw .png.
This would be much appreciated.

website: have website point to lts_schedule #493

---

README.md

We have been back porting specific commits that change style or
code layout that introduce a lot of churn. This has been done to
minimize conflicts moving forward.
I think this may warrant a discussion on if we want to continue this practice

doc: update lts copy regarding changes with churn

---

README.md

Went to create PR to add Sam and Gibson based on recent discussion in: https://github.com/nodejs/LTS/issues/189 and noticed we never actually added a list.
We should have this so people know how to contact for LTS related issues.
We do have a very old PR for a README revamp but its probably stale by now and I think we should add in the members separately.

doc: add list of LTS team members

---

doc/meetings/2017-05-15.md

Fixes: https://github.com/nodejs/LTS/issues/213

doc: add minutes for meeting 2017-05-15

---

README.md

i.e. that there isn't one.
This was agreed in the LTS meeting: https://github.com/nodejs/LTS/issues/213
Continuation of https://github.com/nodejs/LTS/pull/128

doc: clarify maintenance period for odd releases

---

README.md

Currently our schedule specifies exact dates, this can be hard to
commit to. If we plan to be flexible with the dates we chose when
moving a release stream between different levels of support we should
be explicit about it.
This removes all future dates that have currently been decided,
alternatively offering a month in which the event will take place.
It also adds some new language the outlines when individuals should
expect us to give them a date.
- No later than the first of the month the change is happening
- No less than 14 days before the change is happening
I believe that this contract is reasonable and much less likely
to cause miscommunication in the future.
One thing not mentioned in here is how we will be communicating these
dates, and potential changes. We need to decide on a …

meta: updated messaging regarding dates

---

doc/meetings/2017-06-05.md

Closes: https://github.com/nodejs/LTS/issues/225
@nodejs/lts, there was a fair amount of discussion on this one, so please make sure I didn't misrepresent anyone.
If you have any changes to make just click the edit button and add commits using the GitHub interface.

doc: add minutes for meeting 2017-06-05

---

doc/meetings/2017-06-26.md

Closes: https://github.com/nodejs/LTS/issues/233

doc: add minutes for meeting 2017-06-26

---

doc/meetings/2017-03-13.md
doc/meetings/2017-04-24.md
doc/meetings/2017-05-15.md
doc/meetings/2017-06-05.md
doc/meetings/2017-09-19.md

Fixes: https://github.com/nodejs/Release/issues/253
cc/  @mjomble, let me know if this LGTY. 
You can check the meeting issues here: https://github.com/nodejs/Release/issues?q=is%3Aissue+is%3Aclosed+label%3Alts-meeting

doc: fix meeting minute dates

---

README.md

Also gets rid of the dangling `1` on the anchor link.

doc: update support table -- less wordy now

---

doc/meetings/2015-06-18.md

Currently they live in nodejs/nodejs.org, and are not listed here.

doc: add missing meeting minutes from 2015-06-18

---

README.md

Also changes `Active` and `Maintenance` to `Active LTS` and
`Maintenance LTS`.
Fixes: https://github.com/nodejs/Release/issues/257

doc: move Node 8.x to Active LTS

---

doc/meetings/2015-06-11.md

Currently they live in nodejs/nodejs.org, and are not listed here. Followup to #268, this should be the last one to move over.
cc @gibfahn

doc: add missing meeting minutes from 2015-06-11

---

README.md

Also changes to sort members by Github ID.
Refs: nodejs/node#16620

doc: add Gibson Fahnestock to the Releasers team

---

README.md

8.x is now in active LTS, and the OpenSSL version is still 1.0.2.
I think. The [OpenSSL README](https://github.com/nodejs/node/blob/v8.x/deps/openssl/openssl/README#L2) in `deps/openssl/openssl` says:
> OpenSSL 1.0.2m 2 Nov 2017

Remove the note about 8.x’s maintenance LTS support being extended

---

README.md

I'm still on the releasers team, but I have not been active in either the LTS backporting efforts or CITGM and I will be focusing on more forward looking issues for the foreseeable future.

Moving myself to emeritus for LTS and CITGM members

---

README.md

@al-k21 has been pretty active in CitGM recently, and it would be useful for him to have CI access etc.
cc/ @nodejs/citgm

Add Oleksandr Kushchak to the CitGM team

---

CODENAMES.md
README.md

Fixes: https://github.com/nodejs/Release/issues/317

add CODENAMES.md

---

README.md

2018-06-30 has passed, it's July now.
_That depends on the time zone you are in, but there won't be any more 9.x releases afaik._
_Also, this needs time to land._

doc: move v9.x to EOL

---

README.md

This is a much more efficient and reliable way of doing this imho.
One thing I am noticing with this is that we currently only have subteams, not a single master list. is that something we would want? I personally think what we have is solid but it is worth asking the question.
There are also a bunch of folks that are on the LTS team who have not been active lately. This is likely due to us no longer having regular release team meetings. I would like to start doing a monthly release team meeting with people from all sub groups. 
I'm pinging all people from all subteams, do you still want to be involved in release / lts?
- [@al-k21](https://github.com/al-k21) - Oleksandr Kushchak
- [@addaleax](https://github.com/addaleax) - Anna Henningsen
- [@bengl](https://github.com/bengl) - Bryan …

chore: use ncu-team to sync memberlist

---

GOVERNANCE.md

Currently we require 3 releases to be prepared, and only on the current
release branch. This seems to be causing a backlog in onboarding.
/cc @nodejs/releasers any concerns with this change?

governance: only require preparing one release for releasers

---

README.md

Nodejs 10.x started Active LTS mode today #381

changing 10.x status to Active LTS in Release schedule

---

doc/meetings/2015-06-29.md

Was recorded under my soon to be inactive NodeSource account, archived under the Node.js Foundation account for posterity.
Ref https://github.com/nodejs/TSC/pull/631

doc: switch to archived version of an rvagg meeting

---

README.md

Refs: https://github.com/nodejs/node/pull/24465

doc: be explicit about who can land on staging

---

README.md

Use "Active LTS" instead.
Fixes: https://github.com/nodejs/Release/issues/147

doc: remove confusing wording regarding NAN

---

README.md

If I am not mistaken, either the Emeritus list has to be fixed
or the current members list.
cc @jasnell

reflect James's current status correctly

---

README.md

This updates a statement that odd-numbered releases are fully EOL once the next even-numbered release is cut. This seems to be reflected in the [release schedule](https://github.com/nodejs/Release/blob/master/schedule.json#L44), and in a [twitter thread](https://twitter.com/MylesBorins/status/989191105152520192) discussing this topic.

Update statement on odd-numbered updates

---

GOVERNANCE.md

Coming out of https://github.com/nodejs/Release/issues/390 I've done some updating of the process for adding new releasers.
Clean-up, plus I've Added:
* Guidance on SSH key complexity and how to make one
* Notes about SSH & GPG key compromise
* Rules for starting new LTS releases (start with a Current)
The one thing I'm not sure about, but is already in here, is why all new releasers get added to nodejs-private? Perhaps that should be a separate step so as to give us more flexibility in adding releasers outside of the TSC while not expanding nodejs-private access too much. Security releases are a major ordeal and more important than even LTS releases to get right. And in practice, very few of us even do them because of the massive workload and complexity involved—and past experimentation …

doc: update the releaser onboarding process and rules

---

README.md

Update to indicate that changes for N-API will be allowed
in Maintenance when necessary.
In the last release WG meeting I took the issue to open this.

doc: update to reflect N-API

---

README.md

According to the release schedule, 11.x is End-of-Life starting at the 2019-06-01.
This commit reflects this change in the `README.md` by moving 11.x from the Release schedule to the End-of-Life Releases.
Fixes https://github.com/nodejs/Release/issues/453

doc: transfer 11.x to End-of-Life Releases

---

README.md
schedule.json

Draft because I think it shouldn't land before 12.13.0 is released.

schedule: give v12.x LTS its codename

---

README.md

The fact that moving to an LTS release is semver-minor was missed previously in the policy

meta: document that LTS releases are semver-minor

---

README.md

Outline that the LTS release can happen either before or after
the current release is cut.
Closes: https://github.com/nodejs/Release/issues/495

doc: clarify LTS bit flip process

---

README.md

This is to keep the list up to date. Requested in
https://github.com/nodejs/Release/issues/499#issuecomment-555097166

doc: move Evan Lucas to emeritus

---

README.md

Noticed a markdown reference wasn't working as intended while skimming through the README.. A tiny `)` had slipped into the markdown reference in the wrong place near the Marking a Release Line as LTS section.

Fix markdown reference to Marking as LTS

---

README.md

Remove directions for marking release as LTS from `Release` repo. First step, for https://github.com/nodejs/Release/issues/530.
Docs moved to here: https://github.com/nodejs/node/pull/31724

Remove section for marking release LTS

---

README.md
schedule.json

Adds the date scheduled (2020-04-30) for moving Node 10 into maintenance mode. Changes reflected in the `README.md` schedule and the `schedule.json`.
Discussed with @BethGriggs and @MylesBorins, and settled on this date.

doc: add Maintenance start date for Node 10

---

README.md

I'm involved a bit, but don't require any additional access/membership. Cf. #547

doc: move @sam-github to emeritus

---

README.md

Please let me know if you think this should be moved elsewhere.

doc: add 'Release Phases' documentation

---

README.md

Sam's link is incorrect since he moved himself to emeriti, and we probably don't want it pointing to someone else in case someone acquires the (incorrect) username.

doc: fix link to emeritus member

---

README.md

The headers on the team groupings appear that the LTS team houses backport, releasers, and citgm; so the header tags have been adjusted to match the actual groupings (lts, releasers, citgm).

doc: fix headers in team groupings

---

doc/meetings/2021-02-25.md

Fixes: https://github.com/nodejs/Release/issues/648

doc: add minutes for 2021-02-25

---

GOVERNANCE.md

Creating an offboarding policy for @nodejs/releasers  has been on our list for a while (https://github.com/nodejs/Release/issues/542), so I thought i'd take a first cut.
Also somewhat related: https://github.com/nodejs/Release/issues/499

doc: add offboarding releasers guidance

---

doc/meetings/2021-03-11.md

Fixes: https://github.com/nodejs/Release/issues/651

doc: add minutes for 2021-03-11

---

GOVERNANCE.md

Fixes: https://github.com/nodejs/Release/issues/595

doc: add note to cover backporting GPG keys

---

README.md

Today is 2021-06-01, which is the date v15.x release line is marked as End-of-Life.

Update version table in README

---

README.md

While I had an initial flurry of activity on the CITGM project (5 years ago I think?) I haven't been involved with it since then. While I don't want to rule out any future activity, it's probably well overdue that I step down from that team more officially since my activity there is zero and has been for years. It's certainly possible (maybe even likely?) that this should be reversed in the future, but I'd rather reflect reality now, even if it's several years late.
I couldn't find an offboarding process for CITGM specifically, so I assume this PR suffices. Once it lands, I'll remove myself from the @nodejs/citgm .

Move myself from CITGM to CITGM Emeritus

---

README.md

Refs: https://github.com/nodejs/Release/issues/495
----
This reflects what we've done intentionally for the past few LTS releases.

doc: ensure LTS promotion after the new major release

---

GOVERNANCE.md

Having just gone through this process, some clarification was warranted, and two new ones were added:
* Adding gpg key to `nodejs/release-keys`
* Adding themself in this repo's README

doc: clarify and update releaser onboarding steps

---

README.md

From our conversation in #nodejs-release.
Should it be included somehow in the https://github.com/nodejs/node/blob/main/doc/contributing/releases.md too?

doc: include revert option

---

README.md

"Releasers have access to critical infrastructure in the project - this elevated access must be restricted to active releasers. Members of the releasers team should be offboarded when they no longer intend to prepare releases. As a guideline, offboarding should be considered if a releaser has not prepared a release in the past 12 months."
Refs: https://github.com/nodejs/Release/blob/main/GOVERNANCE.md#offboarding-releasers

chore: move inactive releasers to emeritus

---

README.md
schedule.json

Given that v18 is turning LTS in v18.12.0 this change updates the initial table located in the README of the repo in order to mark v18 as being an LTS version along with adding its codename reference.
Refs: https://github.com/nodejs/node/pull/45100

doc: update Hydrogen LTS status on readme

---

README.md

doc: ncu-team sync update

---

GOVERNANCE.md

This is a change in the policy to highlight that is recommend to avoid self-nomination as a releaser. 
Please feel free to suggest any change in the wording 🙏

docs: update nomination policy

---

GOVERNANCE.md

Related: https://github.com/nodejs/Release/issues/965

docs: add GPG validation onboarding step

---

CODENAMES.md

Extend codenames for a further six releases through to Node.js 34, which takes us to 2030.
By convention, all of our long term support codenames have been chemical elements.
No immediate rush to land this (we have Jod for Node.js 22 next year). I'll leave some alternative suggestions (existing elements) as in-line reviews.

doc: add codenames through to Node.js 34 (2030)

---

GOVERNANCE.md
README.md

Fixes: https://github.com/nodejs/Release/issues/1012
@nodejs/releasers

chore: remove lts team

---

doc/meetings/2025-06-26.md

Please review your notes if possible @RafaelGSS @richardlau @aduh95 @marco-ippolito, I'll try to update the PR with the recording once the video is uploaded to Youtube.

doc: add minutes for meeting 2025-06-26
